import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  X, 
  Camera, 
  QrCode, 
  CheckCircle2, 
  AlertTriangle, 
  RotateCcw, 
  Sparkles, 
  ShieldCheck, 
  User, 
  FileText, 
  Calendar,
  Zap,
  Info,
  Copy,
  ExternalLink,
  ShieldAlert,
  HelpCircle,
  Clock,
  Check,
  WifiOff
} from 'lucide-react';
import jsQR from 'jsqr';
import { MtcPass } from '../types';

interface QrScannerOverlayProps {
  isOpen: boolean;
  onClose: () => void;
  pass: MtcPass;
}

type ScannerScreenType = 'scanning' | 'result' | 'error';
type ParsedType = 'pass' | 'url' | 'text';

interface ParsedPassData {
  passNo: string;
  name: string;
  type: string;
  validTo: string;
  amount: string;
  status: string;
}

interface ScanResult {
  type: ParsedType;
  data: string | ParsedPassData;
}

export default function QrScannerOverlay({ isOpen, onClose, pass }: QrScannerOverlayProps) {
  const [screenState, setScreenState] = useState<ScannerScreenType>('scanning');
  const [permissionState, setPermissionState] = useState<'prompt' | 'granted' | 'denied' | 'checking'>('prompt');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [flashlight, setFlashlight] = useState<boolean>(false);
  const [stream, setStream] = useState<MediaStream | null>(null);
  const [copied, setCopied] = useState<boolean>(false);
  
  // Results state
  const [qrResult, setQrResult] = useState<ScanResult | null>(null);
  const [rawText, setRawText] = useState<string>('');

  const videoRef = useRef<HTMLVideoElement | null>(null);
  const activeStreamRef = useRef<MediaStream | null>(null);

  // Helper to parse the decrypted QR content
  const parseQrContent = (content: string): ScanResult => {
    const trimmed = content.trim();

    // 1. JSON-based pass data
    try {
      if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
        const parsed = JSON.parse(trimmed);
        if (parsed.passNo || parsed.name || parsed.type || parsed.validTo) {
          return {
            type: 'pass',
            data: {
              passNo: parsed.passNo || 'MTC-SCAN-9988',
              name: parsed.name || 'Unknown Passenger',
              type: parsed.type || 'MTC Transit Pass',
              validTo: parsed.validTo || '01/09/2026',
              amount: parsed.amount || 'Subsidized',
              status: parsed.status || 'Active'
            }
          };
        }
      }
    } catch (e) {
      // Fall through if not valid JSON
    }

    // 2. Structured plain text MTC passes (like the ones generated by the card QR code generator)
    if (trimmed.includes('MTC-PASS') || trimmed.includes('MTC-PASS-VERIFIED') || trimmed.includes('No:') && trimmed.includes('Valid To:')) {
      const lines = trimmed.split('\n');
      const passData: Partial<ParsedPassData> = {};
      
      lines.forEach(line => {
        const cleanLine = line.trim();
        const lowerLine = cleanLine.toLowerCase();
        
        if (lowerLine.startsWith('no:') || lowerLine.startsWith('passno:') || lowerLine.startsWith('pass no:')) {
          passData.passNo = cleanLine.split(':').slice(1).join(':').trim();
        } else if (lowerLine.startsWith('name:')) {
          passData.name = cleanLine.split(':').slice(1).join(':').trim();
        } else if (lowerLine.startsWith('type:') || lowerLine.startsWith('category:')) {
          passData.type = cleanLine.split(':').slice(1).join(':').trim();
        } else if (lowerLine.startsWith('valid to:') || lowerLine.startsWith('validto:') || lowerLine.startsWith('valid:')) {
          passData.validTo = cleanLine.split(':').slice(1).join(':').trim();
        } else if (lowerLine.startsWith('amount:') || lowerLine.startsWith('fare:') || lowerLine.startsWith('price:')) {
          passData.amount = cleanLine.split(':').slice(1).join(':').trim();
        } else if (lowerLine.startsWith('status:')) {
          passData.status = cleanLine.split(':').slice(1).join(':').trim();
        }
      });

      if (passData.passNo || passData.name || passData.type || passData.validTo) {
        return {
          type: 'pass',
          data: {
            passNo: passData.passNo || 'MTC-SCAN-9911',
            name: passData.name || 'MTC Passenger',
            type: passData.type || 'Standard Pass',
            validTo: passData.validTo || '01/09/2026',
            amount: passData.amount || '₹1000',
            status: passData.status || 'Active'
          }
        };
      }
    }

    // 3. Web URL
    const urlPattern = /^(https?:\/\/[^\s]+)$/i;
    if (urlPattern.test(trimmed)) {
      return {
        type: 'url',
        data: trimmed
      };
    }

    // 4. Default plain text fallback
    return {
      type: 'text',
      data: content
    };
  };

  // Triggers when QR code is found
  const handleQrCodeDetected = (text: string) => {
    // 1. Instantly stop camera tracks
    stopCamera();
    
    // 2. Process and parse content
    setRawText(text);
    const parsed = parseQrContent(text);
    setQrResult(parsed);
    setScreenState('result');

    // Trigger subtle success haptic vibration if supported on device
    if (navigator.vibrate) {
      navigator.vibrate([100, 50, 100]);
    }
  };

  // Start the physical camera feed
  const startCamera = async () => {
    setPermissionState('checking');
    setScreenState('scanning');
    setErrorMessage(null);
    setQrResult(null);
    setFlashlight(false);

    try {
      // Request permissions immediately for back camera
      const mediaStream = await navigator.mediaDevices.getUserMedia({
        video: { 
          facingMode: { ideal: 'environment' },
          width: { ideal: 1280 },
          height: { ideal: 720 }
        }
      });

      activeStreamRef.current = mediaStream;
      setStream(mediaStream);
      setPermissionState('granted');

      // Hook up to the video DOM element
      if (videoRef.current) {
        videoRef.current.srcObject = mediaStream;
      }
    } catch (err: any) {
      console.error('Camera capture failed:', err);
      setPermissionState('denied');
      setScreenState('error');

      if (err.name === 'NotAllowedError' || err.name === 'PermissionDeniedError') {
        setErrorMessage('Camera access was denied by your browser or operating system. To scan transit passes, please click the site permission settings in your browser address bar and enable camera access.');
      } else if (err.name === 'NotFoundError' || err.name === 'DevicesNotFoundError') {
        setErrorMessage('No camera hardware was detected on this device. If you are on a desktop PC, please connect a webcam or use our testing simulator below.');
      } else {
        setErrorMessage(`Unable to access camera stream: ${err.message || 'Unknown device error'}. You can still use our interactive tester panel below.`);
      }
    }
  };

  // Release camera resources safely
  const stopCamera = () => {
    if (activeStreamRef.current) {
      activeStreamRef.current.getTracks().forEach(track => track.stop());
      activeStreamRef.current = null;
    }
    setStream(null);
  };

  // Trigger camera startup when opened
  useEffect(() => {
    if (isOpen) {
      startCamera();
    } else {
      stopCamera();
    }

    return () => {
      stopCamera();
    };
  }, [isOpen]);

  // Real-time Frame Analysis Loop (Throttled for Performance)
  useEffect(() => {
    if (!isOpen || permissionState !== 'granted' || !stream || screenState !== 'scanning') return;

    let isScanningActive = true;
    let scanTimeout: any = null;

    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d', { willReadFrequently: true });

    const grabAndScanFrame = () => {
      if (!isScanningActive) return;

      const video = videoRef.current;
      if (video && video.readyState === video.HAVE_ENOUGH_DATA && ctx) {
        // Adjust canvas dimension to match video source aspect
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        
        // Draw video frame onto offscreen buffer
        ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
        
        try {
          const imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
          
          // Call the jsQR decoder
          const decoded = jsQR(imgData.data, imgData.width, imgData.height, {
            inversionAttempts: 'dontInvert'
          });

          if (decoded && decoded.data) {
            handleQrCodeDetected(decoded.data);
            return; // Exit loop, scanner found code
          }
        } catch (e) {
          console.warn("Frame analysis draw skipped:", e);
        }
      }

      // Throttled frame grab: 150ms delay keeps CPU overhead low while remaining fully responsive
      scanTimeout = setTimeout(grabAndScanFrame, 150);
    };

    // Kick off loop with small initialization buffer
    scanTimeout = setTimeout(grabAndScanFrame, 350);

    return () => {
      isScanningActive = false;
      if (scanTimeout) clearTimeout(scanTimeout);
    };
  }, [isOpen, permissionState, stream, screenState]);

  // Handle flashlight/torch toggle
  const toggleFlashlight = async () => {
    if (!stream) return;
    const videoTrack = stream.getVideoTracks()[0];
    if (!videoTrack) return;

    try {
      const trackCaps = videoTrack.getCapabilities() as any;
      if (trackCaps.torch) {
        const nextFlashState = !flashlight;
        await videoTrack.applyConstraints({
          advanced: [{ torch: nextFlashState }] as any
        });
        setFlashlight(nextFlashState);
      } else {
        // Simulate flashlight status if physical torch is not supported on the browser
        setFlashlight(!flashlight);
      }
    } catch (e) {
      console.warn("Camera torch apply failed (benign hardware restriction):", e);
      setFlashlight(!flashlight);
    }
  };

  // Clipboard copies
  const handleCopyText = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Opening plain links safely
  const handleOpenLink = (url: string) => {
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  // Mock Simulations for local preview environments & systems without active camera access
  const handleSimulateScan = (mode: 'valid' | 'expired' | 'url' | 'text') => {
    if (mode === 'valid') {
      const mockData = `MTC-PASS-VERIFIED\nNo: ${pass.passNo}\nName: ${pass.name}\nType: ${pass.type}\nValid To: ${pass.validTo}\nAmount: ${pass.amount}\nStatus: Active`;
      handleQrCodeDetected(mockData);
    } else if (mode === 'expired') {
      const mockData = `MTC-PASS-VERIFIED\nNo: MTC-EXP-4890\nName: ${pass.name}\nType: Monthly Pass\nValid To: 14/07/2026\nAmount: ₹1000\nStatus: Expired`;
      handleQrCodeDetected(mockData);
    } else if (mode === 'url') {
      handleQrCodeDetected('https://chennaimetroland.com/mtc-transit-advisory');
    } else {
      handleQrCodeDetected('MTC General Information Service:\nStandard single journey fare on Deluxe Bus is ₹24.00.\nAlways buy valid tickets or possess an active digitized pass.');
    }
  };

  if (!isOpen) return null;

  return (
    <div className="absolute inset-0 bg-slate-950 z-50 flex flex-col justify-between p-5 font-sans overflow-hidden select-none" id="real-qr-scanner-screen">
      
      {/* 1. TOP HEADER STATUS */}
      <div className="flex justify-between items-center z-20 shrink-0">
        <div className="flex items-center gap-2 text-white">
          <div className="w-2.5 h-2.5 rounded-full bg-red-500 animate-pulse" />
          <div>
            <h3 className="text-xs font-bold tracking-widest font-mono text-slate-200">MTC-SECURE-SCAN v5.0</h3>
            <p className="text-[9px] text-slate-400 font-mono uppercase tracking-wider">Device Camera Terminal</p>
          </div>
        </div>
        <button 
          onClick={onClose}
          className="p-2 rounded-full bg-slate-900/90 border border-slate-800 text-slate-300 hover:text-white active:scale-90 transition-all cursor-pointer shadow-md"
          id="scanner-close-btn"
        >
          <X className="w-5 h-5" />
        </button>
      </div>

      {/* 2. BODY FRAME SWITCHBOARD */}
      <div className="flex-grow flex flex-col items-center justify-center my-4 relative w-full">
        <AnimatePresence mode="wait">
          
          {/* VIEWPORT A: SCANNING CAMERA VIEW */}
          {screenState === 'scanning' && permissionState === 'granted' && (
            <motion.div 
              key="camera-viewport-container"
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 rounded-[32px] overflow-hidden bg-slate-950 border border-slate-900 shadow-2xl flex items-center justify-center"
            >
              {/* Full background video viewport */}
              <video 
                ref={videoRef}
                playsInline
                autoPlay
                muted
                className="absolute inset-0 w-full h-full object-cover"
              />

              {/* Real-time Rec Badge metric overlay */}
              <div className="absolute top-4 left-4 text-[9px] font-mono text-red-500 font-extrabold flex items-center gap-1.5 z-10 bg-slate-950/80 px-2.5 py-1 rounded-full border border-red-500/20">
                <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-ping shrink-0" />
                <span>LIVE FEED REC @60FPS</span>
              </div>

              {/* High-tech Centered Mask cutout using huge box shadow */}
              <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none z-10">
                <div 
                  className="w-60 h-60 border-2 border-[#ff0055] rounded-[32px] relative overflow-hidden shadow-[0_0_0_9999px_rgba(10,10,14,0.7)]"
                  style={{
                    boxShadow: '0 0 0 9999px rgba(10,10,14,0.7), inset 0 0 15px rgba(255,0,85,0.2)'
                  }}
                >
                  {/* Neon laser sweeps */}
                  <motion.div 
                    initial={{ top: '4%' }}
                    animate={{ top: '96%' }}
                    transition={{ 
                      repeat: Infinity, 
                      repeatType: 'reverse', 
                      duration: 1.6,
                      ease: 'easeInOut'
                    }}
                    className="absolute inset-x-0 h-[2.5px] bg-[#ff0055] shadow-[0_0_12px_#ff0055]"
                  />

                  {/* High contrast Gold corner brackets */}
                  <div className="absolute top-0 left-0 w-6 h-6 border-t-4 border-l-4 border-amber-400 rounded-tl-[16px]" />
                  <div className="absolute top-0 right-0 w-6 h-6 border-t-4 border-r-4 border-amber-400 rounded-tr-[16px]" />
                  <div className="absolute bottom-0 left-0 w-6 h-6 border-b-4 border-l-4 border-amber-400 rounded-bl-[16px]" />
                  <div className="absolute bottom-0 right-0 w-6 h-6 border-b-4 border-r-4 border-amber-400 rounded-br-[16px]" />
                </div>

                <div className="mt-5 flex flex-col items-center justify-center gap-1">
                  <p className="text-white text-[11px] font-black tracking-wider uppercase bg-slate-950/90 px-3.5 py-1.5 rounded-full border border-slate-800 shadow-lg">
                    Align Code Inside Grid Frame
                  </p>
                  <p className="text-[9px] text-slate-400 font-medium tracking-wide">Scanning is fully automated</p>
                </div>
              </div>

              {flashlight && (
                <div className="absolute inset-0 bg-white/5 pointer-events-none mix-blend-overlay z-10" />
              )}
            </motion.div>
          )}

          {/* VIEWPORT B: SCAN RESULTS DECODED SCREEN */}
          {screenState === 'result' && qrResult && (
            <motion.div 
              key="result-viewport-panel"
              initial={{ opacity: 0, y: 15, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0 }}
              className="w-full max-w-[360px] flex flex-col items-center justify-center gap-5 z-10"
            >
              {/* Outcome Header Badge */}
              <div className="text-center space-y-1.5">
                <div className="inline-flex items-center gap-1.5 bg-emerald-500/10 text-emerald-400 text-[10px] font-black uppercase tracking-widest px-3 py-1 rounded-full border border-emerald-500/30">
                  <CheckCircle2 className="w-3.5 h-3.5 shrink-0" /> Code Decoded
                </div>
                <h2 className="text-lg font-display font-black text-white tracking-wide">Scan Verification Report</h2>
              </div>

              {/* CARD FORMAT: Structured transit pass data */}
              {qrResult.type === 'pass' && (() => {
                const passData = qrResult.data as ParsedPassData;
                const isPassExpired = passData.status?.toLowerCase() === 'expired' || passData.validTo?.includes('2025') || passData.validTo?.includes('14/07/2026');
                
                return (
                  <div className="w-full relative flex flex-col items-center justify-center">
                    
                    {/* The Gold/Yellow Scanned Pass Card Wrapper (Matches original style) */}
                    <div 
                      className="relative w-full max-w-[320px] aspect-[1/1.5] rounded-[36px] p-5 shadow-2xl flex flex-col justify-between overflow-hidden"
                      style={{
                        background: isPassExpired 
                          ? 'linear-gradient(135deg, #4c1d24 0%, #2e1014 50%, #1a0508 100%)' 
                          : 'linear-gradient(135deg, #fce074 0%, #dbb030 50%, #ad8010 100%)',
                        boxShadow: isPassExpired
                          ? '0 20px 40px rgba(220, 38, 38, 0.15)'
                          : '0 20px 40px rgba(173, 128, 16, 0.35)',
                        border: isPassExpired ? '1px solid rgba(220, 38, 38, 0.2)' : 'none'
                      }}
                    >
                      {/* Grid overlay */}
                      <div 
                        className="absolute inset-0 pointer-events-none opacity-[0.14]"
                        style={{
                          backgroundImage: 'radial-gradient(#1e293b 15%, transparent 15%)',
                          backgroundSize: '12px 12px'
                        }}
                      />

                      {/* Header details */}
                      <div className="flex flex-col items-center text-center z-10">
                        <div className="text-[8px] font-black uppercase tracking-widest bg-slate-950/20 text-slate-900 rounded-full px-2 py-0.5 mb-1 font-mono">
                          MTC SECURE LEDGER PASS
                        </div>
                        <h3 className="font-sans font-extrabold text-slate-900 text-base tracking-wide">
                          PASS NO: <span className="font-mono text-slate-950 text-lg">{passData.passNo}</span>
                        </h3>
                      </div>

                      {/* White center credentials frame */}
                      <div className="bg-slate-950 rounded-2xl p-4 border border-slate-800 text-left space-y-2 font-mono text-xs z-10 text-slate-300 w-full">
                        <div className="flex justify-between items-center border-b border-slate-800 pb-1.5">
                          <span className="text-slate-500 text-[10px]">PASSENGER NAME</span>
                          <span className="text-slate-100 font-extrabold font-sans text-[11px] truncate max-w-[140px]">
                            {passData.name}
                          </span>
                        </div>
                        
                        <div className="flex justify-between items-center border-b border-slate-800 pb-1.5">
                          <span className="text-slate-500 text-[10px]">PASS CATEGORY</span>
                          <span className="text-amber-400 font-extrabold text-[11px]">
                            {passData.type}
                          </span>
                        </div>

                        <div className="flex justify-between items-center border-b border-slate-800 pb-1.5">
                          <span className="text-slate-500 text-[10px]">VALIDITY UNTIL</span>
                          <span className={`font-extrabold text-[11px] ${isPassExpired ? 'text-red-400' : 'text-emerald-400'}`}>
                            {passData.validTo}
                          </span>
                        </div>

                        <div className="flex justify-between items-center">
                          <span className="text-slate-500 text-[10px]">FARE VALUE</span>
                          <span className="text-slate-100 font-black">
                            {passData.amount}
                          </span>
                        </div>
                      </div>

                      {/* Expired / Active verification badge banner */}
                      <div className="z-10 w-full flex items-center justify-center pt-2">
                        {isPassExpired ? (
                          <div className="flex items-center gap-1.5 bg-red-500/10 text-red-400 text-[10px] font-black px-4 py-1.5 rounded-full border border-red-500/30 uppercase tracking-widest shadow-sm">
                            <ShieldAlert className="w-3.5 h-3.5" /> Suspended / Expired
                          </div>
                        ) : (
                          <div className="flex items-center gap-1.5 bg-emerald-500/10 text-emerald-400 text-[10px] font-black px-4 py-1.5 rounded-full border border-emerald-500/30 uppercase tracking-widest shadow-sm">
                            <ShieldCheck className="w-3.5 h-3.5" /> Cryptographic Verified
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })()}

              {/* URL FORMAT: Simple Decoded link display */}
              {qrResult.type === 'url' && (
                <div className="w-full bg-slate-900 border border-slate-800 rounded-3xl p-5 space-y-4 shadow-xl text-left">
                  <div className="flex items-center gap-2">
                    <div className="p-2 rounded-xl bg-blue-500/10 text-blue-400 border border-blue-500/20">
                      <ExternalLink className="w-4 h-4" />
                    </div>
                    <div>
                      <h4 className="text-xs font-black text-slate-300 uppercase tracking-wider">Web Link Detected</h4>
                      <p className="text-[10px] text-slate-500 font-mono">Hypertext Transfer Protocol</p>
                    </div>
                  </div>

                  <div className="bg-slate-950 p-3 rounded-2xl border border-slate-900 break-all font-mono text-xs text-blue-400 underline leading-normal shadow-inner">
                    {qrResult.data as string}
                  </div>

                  <div className="flex gap-2.5 pt-1">
                    <button 
                      onClick={() => handleCopyText(qrResult.data as string)}
                      className="flex-1 py-2.5 bg-slate-800 hover:bg-slate-700 active:scale-95 transition-all text-xs font-bold rounded-xl text-white border border-slate-700 flex items-center justify-center gap-1.5 cursor-pointer shadow-sm"
                    >
                      {copied ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-emerald-400" />
                          <span>Copied!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5 text-slate-300" />
                          <span>Copy URL</span>
                        </>
                      )}
                    </button>
                    <button 
                      onClick={() => handleOpenLink(qrResult.data as string)}
                      className="flex-1 py-2.5 bg-[#ff0055] hover:bg-[#db0048] active:scale-95 transition-all text-xs font-bold rounded-xl text-white flex items-center justify-center gap-1.5 cursor-pointer shadow-sm shadow-[#ff0055]/10"
                    >
                      <span>Open Link</span>
                      <ExternalLink className="w-3.5 h-3.5 text-white/90" />
                    </button>
                  </div>
                </div>
              )}

              {/* TEXT FORMAT: Plain Decoded Text details */}
              {qrResult.type === 'text' && (
                <div className="w-full bg-slate-900 border border-slate-800 rounded-3xl p-5 space-y-4 shadow-xl text-left">
                  <div className="flex items-center gap-2">
                    <div className="p-2 rounded-xl bg-amber-500/10 text-amber-400 border border-amber-500/20">
                      <FileText className="w-4 h-4" />
                    </div>
                    <div>
                      <h4 className="text-xs font-black text-slate-300 uppercase tracking-wider">Raw Text Decoded</h4>
                      <p className="text-[10px] text-slate-500 font-mono">Standard String Buffer</p>
                    </div>
                  </div>

                  <div className="bg-slate-950 p-4 rounded-2xl border border-slate-900 text-xs text-slate-200 leading-relaxed font-mono whitespace-pre-wrap max-h-48 overflow-y-auto no-scrollbar shadow-inner border-l-2 border-l-amber-500">
                    {qrResult.data as string}
                  </div>

                  <div className="pt-1">
                    <button 
                      onClick={() => handleCopyText(qrResult.data as string)}
                      className="w-full py-2.5 bg-slate-800 hover:bg-slate-700 active:scale-95 transition-all text-xs font-bold rounded-xl text-white border border-slate-700 flex items-center justify-center gap-1.5 cursor-pointer shadow-sm"
                    >
                      {copied ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-emerald-400" />
                          <span>Copied String!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5 text-slate-300" />
                          <span>Copy Raw Text</span>
                        </>
                      )}
                    </button>
                  </div>
                </div>
              )}

            </motion.div>
          )}

          {/* VIEWPORT C: CAMERA ACCESS ERROR / PERMISSION DENIED */}
          {screenState === 'error' && (
            <motion.div 
              key="error-viewport-panel"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              className="w-full max-w-[340px] bg-slate-900 border border-slate-800 rounded-[32px] p-6 text-center shadow-xl space-y-4 z-10"
            >
              <div className="w-16 h-16 rounded-2xl bg-rose-500/10 border border-rose-500/20 text-rose-400 flex items-center justify-center mx-auto shadow-md">
                <ShieldAlert className="w-10 h-10 stroke-[1.8]" />
              </div>

              <div className="space-y-1">
                <h3 className="text-base font-display font-black text-white uppercase tracking-wide">Camera Access Blocked</h3>
                <p className="text-[10px] text-slate-500 font-mono">METROPOLITAN TRANSPORT CORP • SECURITY GRID</p>
              </div>

              <p className="text-xs text-slate-400 leading-relaxed font-medium">
                {errorMessage || 'Camera access was blocked or is not supported in this frame environment.'}
              </p>

              <div className="bg-slate-950 p-3.5 rounded-2xl border border-slate-900 text-left text-[10.5px] text-slate-500 space-y-1.5">
                <p className="font-extrabold uppercase text-[8.5px] text-amber-500 tracking-wider">Troubleshooting Steps:</p>
                <div className="space-y-1 leading-normal">
                  <p>1. Check browser lock icon near address bar.</p>
                  <p>2. Ensure other apps aren't locking the camera.</p>
                  <p>3. If inside a preview iframe, click "Open in New Tab" at the top to bypass iframe permission constraints.</p>
                </div>
              </div>

              <button 
                onClick={startCamera}
                className="w-full py-2.5 bg-[#ff0055] hover:bg-[#db0048] active:scale-95 transition-all text-xs font-bold rounded-xl text-white shadow-md cursor-pointer flex items-center justify-center gap-1.5 uppercase tracking-wider"
              >
                <RotateCcw className="w-4 h-4 text-white" /> Try Camera Again
              </button>
            </motion.div>
          )}

        </AnimatePresence>
      </div>

      {/* 3. LOWER CONTROL CONSOLE PANEL (Interactive buttons & simulated testing presets) */}
      <div className="bg-slate-900 border border-slate-800 p-4 rounded-[28px] shrink-0 space-y-4 z-10 shadow-lg">
        {screenState === 'scanning' && permissionState === 'granted' ? (
          <>
            <div className="text-center space-y-1">
              <p className="text-xs font-bold text-slate-300">Point phone at an MTC Pass QR Code</p>
              <p className="text-[9px] text-slate-500 font-mono uppercase tracking-wider">Or run test simulation presets below:</p>
            </div>

            {/* Quick simulated presets inside camera scan layout */}
            <div className="grid grid-cols-4 gap-1.5">
              <button 
                onClick={() => handleSimulateScan('valid')}
                className="py-2 px-1 rounded-xl bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/20 font-bold text-[9px] tracking-wide uppercase transition-all flex flex-col items-center justify-center gap-1 cursor-pointer"
                title="Simulate scanning a valid digitized pass"
              >
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                <span>Valid Pass</span>
              </button>

              <button 
                onClick={() => handleSimulateScan('expired')}
                className="py-2 px-1 rounded-xl bg-amber-500/10 hover:bg-amber-500/20 text-amber-400 border border-amber-500/20 font-bold text-[9px] tracking-wide uppercase transition-all flex flex-col items-center justify-center gap-1 cursor-pointer"
                title="Simulate scanning an expired transit pass"
              >
                <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
                <span>Expired Pass</span>
              </button>

              <button 
                onClick={() => handleSimulateScan('url')}
                className="py-2 px-1 rounded-xl bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 border border-blue-500/20 font-bold text-[9px] tracking-wide uppercase transition-all flex flex-col items-center justify-center gap-1 cursor-pointer"
                title="Simulate scanning a plain web link"
              >
                <ExternalLink className="w-3.5 h-3.5 text-blue-400" />
                <span>Web Link</span>
              </button>

              <button 
                onClick={() => handleSimulateScan('text')}
                className="py-2 px-1 rounded-xl bg-purple-500/10 hover:bg-purple-500/20 text-purple-400 border border-purple-500/20 font-bold text-[9px] tracking-wide uppercase transition-all flex flex-col items-center justify-center gap-1 cursor-pointer"
                title="Simulate scanning plain static text"
              >
                <FileText className="w-3.5 h-3.5 text-purple-400" />
                <span>Plain Text</span>
              </button>
            </div>

            {/* Flashlight/Torch Controls */}
            <div className="flex justify-center pt-1 border-t border-slate-800">
              <button 
                onClick={toggleFlashlight}
                className={`px-4 py-1.5 rounded-full text-[10px] font-bold font-mono border transition-all flex items-center gap-1.5 cursor-pointer ${
                  flashlight 
                    ? 'bg-amber-500 border-amber-500 text-slate-950 shadow-md' 
                    : 'bg-slate-850 border-slate-800 text-slate-400 hover:text-slate-200'
                }`}
              >
                <Zap className="w-3.5 h-3.5" /> FLASHLIGHT: {flashlight ? 'ACTIVE' : 'OFF'}
              </button>
            </div>
          </>
        ) : screenState === 'scanning' && permissionState !== 'granted' ? (
          <>
            {/* If camera is checking or denied, show mock scanning controllers to keep app completely usable */}
            <div className="text-center space-y-1">
              <p className="text-xs font-bold text-slate-300">Camera Access Not Ready</p>
              <p className="text-[9.5px] text-slate-500 leading-normal">Use the interactive simulation panel to test the scanner functionality seamlessly:</p>
            </div>

            <div className="grid grid-cols-2 gap-2">
              <button 
                onClick={() => handleSimulateScan('valid')}
                className="p-3 rounded-xl bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/25 font-bold text-[10.5px] tracking-wide uppercase transition-all flex flex-col items-center justify-center gap-1 cursor-pointer"
              >
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                <span>Simulate Valid Pass</span>
              </button>

              <button 
                onClick={() => handleSimulateScan('expired')}
                className="p-3 rounded-xl bg-amber-500/10 hover:bg-amber-500/20 text-amber-400 border border-amber-500/25 font-bold text-[10.5px] tracking-wide uppercase transition-all flex flex-col items-center justify-center gap-1 cursor-pointer"
              >
                <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0" />
                <span>Simulate Expired Pass</span>
              </button>

              <button 
                onClick={() => handleSimulateScan('url')}
                className="p-3 rounded-xl bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 border border-blue-500/25 font-bold text-[10.5px] tracking-wide uppercase transition-all flex flex-col items-center justify-center gap-1 cursor-pointer"
              >
                <ExternalLink className="w-4 h-4 text-blue-400 shrink-0" />
                <span>Simulate Web Link</span>
              </button>

              <button 
                onClick={() => handleSimulateScan('text')}
                className="p-3 rounded-xl bg-purple-500/10 hover:bg-purple-500/20 text-purple-400 border border-purple-500/25 font-bold text-[10.5px] tracking-wide uppercase transition-all flex flex-col items-center justify-center gap-1 cursor-pointer"
              >
                <FileText className="w-4 h-4 text-purple-400 shrink-0" />
                <span>Simulate Raw Text</span>
              </button>
            </div>
          </>
        ) : (
          /* SCREEN: AFTER SCAN DECODED RESULT SHOWS */
          <div className="flex gap-3">
            <button 
              onClick={startCamera}
              className="flex-1 py-3 bg-slate-800 hover:bg-slate-700 active:scale-98 text-white font-bold text-xs rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer uppercase tracking-wider shadow-sm border border-slate-700"
              id="scanner-scan-again-btn"
            >
              <RotateCcw className="w-4 h-4 text-slate-300" /> Scan Another QR
            </button>
            <button 
              onClick={onClose}
              className="flex-1 py-3 bg-[#ff0055] hover:bg-[#db0048] active:scale-98 text-white font-bold text-xs rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer uppercase tracking-wider shadow-sm shadow-[#ff0055]/20"
              id="scanner-done-btn"
            >
              <CheckCircle2 className="w-4 h-4 text-white" /> Exit Scanner
            </button>
          </div>
        )}
      </div>

    </div>
  );
}
